Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
AllCops:
  Exclude:
    - 'bin/bundle'